/**
 * String.format for JavaScript
 * Copyright (c) Daniel Mester Pirttijärvi 2013
 * 
 * www.masterdata.se/r/string_format_for_javascript/
 */

var msf={version:"1.06"};
(function(){function t(a){return 10>a?n+a:a}function C(a){for(var b in D)a[b]=a[b]||D[b];a.f=a.f||a.D+" "+a.t;a.F=a.F||a.D+" "+a.T;a.g=a.g||a.d+" "+a.t;a.G=a.G||a.d+" "+a.T;a.m=a.M;a.y=a.Y;return a}function E(){msf.LC=z&&(B[z[v]()]||B[z.split("-")[0][v]()])||H}function F(a,b){var g=Math.pow(10,b||0);return""+Math.round(Math.abs(a)*g)/g}function G(a){var b=a.indexOf(".");return 0>b?a.length:b}function r(a,b){for(var g=0,e=b.length;g<e;g++)a.push(b.charAt(g)),1<a.g&&1==a.g--%3&&a.push(a.t)}function u(a,
b){return a.substr(0,(a.length+1-(b||0))/2)}function s(a,b,g,e,f,h){var c=[];c.t=h;0>a&&c.push("-");a=F(a,e);e=c.g=G(a);h=a;var d=h.indexOf(".");h=0>d?0:h.length-d-1;for(b-=e;0<b--;)r(c,n);r(c,a.substr(0,e));if(g||h){c.push(f);r(c,a.substr(e+1));for(g-=h;0<g--;)r(c,n)}return c.join("")}var w=Number,A=String,n="0",v="toUpperCase",D={name:"",d:"MM/dd/yyyy",D:"dddd, dd MMMM yyyy",t:"HH:mm",T:"HH:mm:ss",M:"MMMM dd",Y:"yyyy MMMM",s:"yyyy-MM-ddTHH:mm:ss",_M:"January February March April May June July August September October November December".split(" "),
_D:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),_r:".",_t:",",_c:"\u00a4#,0.00",_ct:",",_cr:".",_am:"AM",_pm:"PM"},H=C({}),z=navigator.systemLanguage||navigator.language||"",B={};w.prototype.__Format=function(a){var b=w(this),g=msf.LC._r,e=msf.LC._t;if(!isFinite(b))return""+b;if(!a&&a!==n)return s(b,0,0,10,g);var f=a.match(/^([a-zA-Z])(\d*)$/);if(f){var h=f[1][v](),c=parseInt(f[2],10),c=15<c?15:c;switch(h){case "D":return s(b,isNaN(c)?1:c,0,0);case "F":e="";case "N":return s(b,
1,isNaN(c)?2:c,isNaN(c)?2:c,g,e);case "G":case "E":a=0;for(var d=Math.abs(b);10<=d;)d/=10,a++;for(;1>d;)d*=10,a--;var f=f[1],k=3;if("G"==h){if(-5<a&&(!c||a<c))return s(b,1,c?c-(0<a?a+1:1):0,c?c-(0<a?a+1:1):10,g);f="G"==f?"E":"e";k=2;h=(c||1)-1;c=(c||11)-1}else h=c=isNaN(c)?6:c;0<=a&&(f+="+");0>b&&(d*=-1);return s(""+d,1,h,c,g,e)+f+s(a,k,0);case "P":return s(100*b,1,isNaN(c)?2:c,isNaN(c)?2:c,g,e)+" %";case "X":b=Math.round(b).toString(16);"X"==f[1]&&(b=b[v]());for(c-=b.length;0<c--;)b=n+b;return b;
case "C":a=msf.LC._c;g=msf.LC._cr;e=msf.LC._ct;break;case "R":return""+b}}-1!==a.indexOf(",.")&&(b/=1E3);-1!==a.indexOf("%")&&(b*=100);c=a.split(";");0>b&&1<c.length?(b*=-1,a=c[1]):a=c[!b&&2<c.length?2:0];var c=a,x=a.match(/^[^\.]*[0#],[0#]/)&&e,l=0,m=e=-1,m=0;a=-1;for(var y=0,d=0,h=1,p=c.length,q=[],k=0;k<p;k++)if(f=c.charAt(k),"'"==f)d=!d;else if(!d){if(f==n||"#"==f)m+=y,f==n&&(y?a=m:0>e&&(e=l)),l+=!y;y=y||"."==f}e=0>e?1:l-e;0>b&&q.push("-");b=F(b,m);m=G(b);k=m-l;q.g=Math.max(m,e);q.t=x;for(x=d=
0;x<p;x++)if(f=c.charAt(x),"'"==f)d=!d;else if(d)q.push(f);else if("#"==f||f==n){if(k<m)0<=k?(h&&r(q,b.substr(0,k)),r(q,b.charAt(k))):k>=m-e&&r(q,n),h=0;else if(0<a--||k<b.length)r(q,k>=b.length?n:b.charAt(k));k++}else"."==f?(b.length>++k||0<a)&&q.push(g):","!==f&&q.push(f);return q.join("")};Date.prototype.__Format=function(a){var b=msf.LC,g=this.getFullYear(),e=this.getMonth(),f=this.getDate(),h=this.getDay(),c=this.getHours(),d=this.getMinutes(),k=this.getSeconds();1==a.length&&(a=b[a]||a);return a.replace(/('[^']*'|d{1,4}|M{1,4}|yyyy|yy|HH?|hh?|mm?|ss?|tt?)/g,
function(a){return"dddd"==a?b._D[h]:"ddd"==a?b._d?b._d[h]:b._D[h].substr(0,3):"dd"==a?t(f):"d"==a?f:"MMMM"==a?b._M[e]:"MMM"==a?b._m?b._m[e]:b._M[e].substr(0,3):"MM"==a?t(e+1):"M"==a?e+1:"yyyy"==a?g:"yy"==a?(""+g).substr(2):"HH"==a?t(c):"H"==a?c:"hh"==a?t((c-1)%12+1):"h"==a?(c-1)%12+1:"mm"==a?t(d):"m"==a?d:"ss"==a?t(k):"s"==a?k:"tt"==a?12>c?b._am:b._pm:"t"==a?(12>c?b._am:b._pm).charAt(0):a.substr(1,a.length-2)})};A.__Format=function(a,b,g,e){var f=arguments;return a.replace(/(\{+)((\d+|[a-zA-Z_$]\w+(?:\.[a-zA-Z_$]\w+|\[\d+\])*)(?:\,(-?\d*))?(?:\:([^\}]*))?)(\}+)|(\{+)|(\}+)/g,
function(){var a=arguments;if(a[7])a=u(a[7]);else if(a[8])a=u(a[8]);else if(0==a[1].length%2||0==a[6].length%2)a=u(a[1])+a[2]+u(a[6]);else{var b=u(a[1],1),d=a[3],e=a[4],g=a[5],l=f,m=parseInt(d,10),n="";if(isNaN(m)){l=l[1];if(null!==l&&void 0!==l)for(var m=/(\.([a-zA-Z_$]\w+)|\[(\d+)\])/g,p=/^[a-zA-Z_$]\w+/.exec(d),l=l[p[0]];null!==l&&void 0!==l&&(p=m.exec(d));)l=l[p[2]||w(p[3])];d=l}else{if(m>l.length-2)throw"Missing argument";d=l[m+1]}d=!(null!==d&&void 0!==d)?"":d.__Format?d.__Format(g):""+d;e=
w(e)||0;for(g=Math.abs(e)-d.length;0<g--;)n+=" ";a=b+(0>e?d+n:n+d)+u(a[6],1)}return a})};msf.LC=null;msf.setCulture=function(a){z=a;E()};msf.registerCulture=function(a){B[a.name[v]()]=C(a);E()};var p=Date.prototype;p.format=p.format||p.__Format;p=w.prototype;p.format=p.format||p.__Format;A.format=A.format||A.__Format})();
